## Description of Project
Recently, many people have been using GenAI such as ChatGPT. 
Although these AI tools are very helpful, they often produce insecure code. 
If you use this code without any filtering, it will be a big problem. 
However, it is not easy to find out whether the code generated by ChatGPT is insecure. 
We want to solve these problems through this project.

## Objective
Analyze the Insecurity of ChatGPT-Generated Code

## Method
* Find a pattern of insecurities, and categorize each vulnerability if possible
* Advice for a possible solution.

## A list of existing team members (Final)
- Seoyoung (Amy) An (**san5**)
- Jihun Kim (**jkim172**)
- Jonathan Skeen (**jskeen6**)
